### ISSUE TITLE
--dest CLI option is unknown

### ISSUE THREAD

**Issue by lokimckay** [atomicojs/exports#5]
```
"@atomico/exports": "^0.36.0",
```

Relevant documentation: [link](https://atomico.gitbook.io/doc/packages/introduction/atomico-exports#dest-less-than-destination-greater-than)

## Output

```shell
> exports src/elements/*/index.ts --dest dist/browser

file:///C:/dev/repo/cc/elements/node_modules/cac/dist/index.mjs:400
          throw new CACError(`Unknown option \`${name.length > 1 ? `--${name}` : `-${name}`}\``);
                ^

CACError: Unknown option `--dest`
```

## Workaround

The `--dist` flag seems to control the destination path, even though the help message says that it is for "Choose a project type"
![image](https://user-images.githubusercontent.com/14341953/182007049-8a727bc6-afe0-477c-8a39-1c5559c7ccae.png)

```shell
exports src/elements/*/index.ts --dist dist/browser
```

**Comment by UpperCod** [comment]
Thanks for your issue, 2 questions:
1. what version of @atomico/exports are you using?
2. Does your package.json have the declaration `"type": "module",`?

**Comment by lokimckay** [comment]
`"@atomico/exports": "^0.36.0",`
Nope, "type" is not defined in my `package.json`

**Comment by UpperCod** [comment]
I apologize, it was something that was not mentioned in the documentation, it is documented now.  Did adding `"type":"module"` solve the problem?
