### ISSUE TITLE
Published npm package contains node_modules

### ISSUE THREAD

**Issue by efoken** [atomicojs/exports#6]
See here, when browsing the code:

https://www.npmjs.com/package/@atomico/exports?activeTab=code

The examples folders **ts-1** and **ts-2** contain node_modules which contains the whole typescript library 2 times. This makes the package about 130MB big!

Please ignore examples when publishing the package – this would save us many megabytes, especially in pipelines 😄

**Comment by UpperCod** [comment]
Hi @efoken  thanks for reporting it, I had ignored editing .npmignore correctly, now it has a size of only 44kb.

One of the interesting things that this version adds is the support for Next13 with @atomico/react, now the wrappers for react now come out with the "use client" prefix automatically
